# เลือกฐานของ image ที่เหมาะสมสำหรับ Node.js เวอร์ชัน 20
FROM node:20-alpine

# ตั้งค่าโฟลเดอร์ที่ใช้ในการทำงาน
WORKDIR /app

# ติดตั้ง dependencies และโค้ดสำหรับ backend
COPY package*.json ./
RUN npm install cors
RUN npm install

COPY . .

# สั่งรัน Node.js บน port 8000
CMD ["node", "index.js"]
